import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import vector from "../public/vector.png";
import bitcoin from "../public/bitcoin.png";
import amazon from "../public/amazon.png";
import notebook from "../public/notebook.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import { useState } from "react";
import ProjectCard from "../components/ProjectCard";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          src="https://unpkg.com/tailwindcss-intersect@1.x.x/dist/observer.min.js"
        ></script>
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen h-[150vh]">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="cursor-pointer text-3xl hover:text-transparent hover:bg-clip-text hover:bg-gradient-to-tr hover:from-red-500 hover:to-orange-600 font-burtons dark:text-white dark:hover:text-transparent dark:hover:bg-clip-text dark:hover:bg-gradient-to-tr dark:hover:from-red-500 dark:hover:to-orange-600 ">
              mrb1nary
            </h1>
            <ul className="flex items-center">
              <li className="cursor-pointer text-xl">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  color={darkMode ? "white" : ""}
                />
              </li>
              <li>
                <a
                  className="transition-all bg-gradient-to-tr from-cyan-500 to-cyan-700 text-white px-4 py-2 rounded-md ml-8 hover:bg-gradient-to-tr hover:from-cyan-700 hover:to-cyan-500"
                  href="/resume.pdf"
                  target="blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-black font-medium md:text-6xl dark:text-white">
              Anubhab Nayak
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-6xl mx-auto dark:text-white">
              Student at Utkal University, currently pursuing Masters in
              Computer Applications. Open to offers for internships and
              full-time roles. I am a self-taught developer and designer. I have
              a passion for learning new things and I am always looking for
              opportunities to improve my skills.
            </p>
          </div>
          <div className="flex justify-center text-5xl gap-16 py-3">
            <a
              href="https://twitter.com/JAnubhab"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillTwitterCircle className="cursor-pointer text-twitter" />
            </a>
            <a
              href="https://github.com/mrb1nary"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillGithub
                className="cursor-pointer"
                color={darkMode ? "white" : ""}
              />
            </a>
            <a
              href="https://www.linkedin.com/in/anubhab-nayak-b84b35112/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin className="cursor-pointer text-linkedin" />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full h-80 w-80 mt-20 p-20 overflow-clip md:w-96 md:h-96">
            <Image
              src={vector}
              alt="avatar"
              objectFit="contain"
              width={1200}
              height={1200}
              layout="fill"
              className="flex justify-center items-center"
            />
          </div>
        </section>

        <div className="translate-y-96 intersect:-translate-y-52 transition-all duration-300 ease-linear h-[150vh]">
          <section className="h-[500px] outline mt-10 flex font-sequel flex-col w-[100%] mb-5 items-center justify-center dark:outline-white">
            <div className="text-black mx-10 my-10 font-extrabold text-5xl dark:text-white">
              SKILLS
            </div>
            <span className="divide-y-8 my-5 mx-auto text-black outline w-[95%] dark:outline-white"></span>
            <div className="text-white mx-auto my-5 font-sans text-5xl flex items-center justify-center gap-5 flex-wrap w-[80%]">
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#DD4B25]">
                HTML
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#254BDD]">
                CSS
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#20232A]">
                React
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#593D88]">
                Redux
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#20232A]">
                NextJS
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#F05033]">
                Git
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#404D59]">
                ExpressJS
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#4EA94B]">
                MongoDB
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#039BE5]">
                Firebase
              </div>
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#363636]">
                Solidity
              </div>
            </div>
          </section>
        </div>

        <div className="translate-y-96 intersect:-translate-y-52 transition-all duration-300 ease-linear h-[150vh]">
          <section className="min-h-[500px] outline mt-10 flex font-sequel flex-col w-[100%] mb-5 items-center justify-center dark:outline-white">
            <div className="text-black mx-10 my-10 font-extrabold text-5xl dark:text-white">
              PROJECTS
            </div>
            <span className="divide-y-8 my-5 mx-auto text-black outline w-[95%] dark:outline-white"></span>
            <div className="text-white mx-auto my-5 font-sans text-5xl flex items-center justify-center gap-5 flex-wrap w-[80%]">
              <div className="outline outline-black outline-2 px-10 py-5 rounded-2xl font-semibold bg-[#DD4B25]">
                <ProjectCard />
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
